name: agro_employee_public
description: "A new Flutter project."

publish_to: "none"

version: 2.2.1+221

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  connectivity_plus: ^6.1.1
  # Tools
  go_router: ^14.6.0
  geolocator: ^11.1.0
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1

  # Map
  google_maps_flutter: ^2.10.0

  # Statemagment
  flutter_riverpod: ^2.6.1

  # Storage
  # flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3

  # Design
  l: ^4.0.2
  dotted_border: ^2.1.0
  dotted_line: ^3.2.3

  # Date_picker
  intl: ^0.19.0
  syncfusion_flutter_datepicker: ^27.1.51
  firebase_core: ^3.9.0
  firebase_remote_config: ^5.2.0
  pretty_dio_logger: ^1.4.0
  http: ^1.2.2
  lottie: ^3.3.1
  mime: ^1.0.6
  http_parser: ^4.0.2
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/lotties/
    - assets/images/user_arrow.png

# Конфигурация для автоматического создания иконок
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/gerb.png"
