name: agro_employee_public
description: "A new Flutter project."

publish_to: "none"

version: 4.2.0+420

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  connectivity_plus: ^7.1.1
  # Tools
  go_router: ^17.3.0
  geolocator: ^14.0.3
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1

  # Map
  google_maps_flutter: ^2.10.0

  # Statemagment
  flutter_riverpod: ^3.3.2

  # Storage
  flutter_secure_storage: ^10.3.1
  shared_preferences: ^2.3.3

  # Design
  l: ^5.0.1
  dotted_border: ^3.1.0
  dotted_line: ^3.2.3
  google_fonts: ^8.1.0
  phosphor_flutter: ^2.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Date_picker
  intl: ^0.20.2
  syncfusion_flutter_datepicker: ^33.2.13
  firebase_core: ^4.10.0
  firebase_remote_config: ^6.5.2
  firebase_messaging: ^16.3.0
  firebase_crashlytics: ^5.2.3
  firebase_analytics: ^12.4.2
  pretty_dio_logger: ^1.4.0
  http: ^1.2.2
  lottie: ^3.3.1
  mime: ^2.0.0
  http_parser: ^4.0.2
  package_info_plus: ^10.1.0
  url_launcher: ^6.3.1
  local_auth: ^3.0.1
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/lotties/
    - assets/images/user_arrow.png
    - assets/uzb-geojson/

# Конфигурация для автоматического создания иконок
# Используется ТОЛЬКО assets/images/gerb.png (только PNG, без XML)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/gerb.png"
  remove_alpha_ios: true
